// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarCountdown: typeof import('@varlet/ui')['_CountdownComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarRate: typeof import('@varlet/ui')['_RateComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}

export { }
